In [1]:
import numpy as np

In [2]:
# This function creates a 2D array using numpy's arange and reshape methods.
ndarray = np.arange(15).reshape(3,5)

In [3]:
ndarray.shape

(3, 5)

In [4]:
ndarray.ndim

2

In [5]:
ndarray.size

15

In [6]:
ndarray.dtype

dtype('int64')

In [7]:
ndarray.itemsize # the size in bytes of each element

8

In [8]:
ndarray.data

## Array Creation

In [9]:
a = np.array([2,3,4])

In [10]:
# transforms sequences of sequences into two-dimensional 
b = np.array([(1.5,2,3), (4,5,6)])
b.ndim

2

In [11]:
# Create an array with zeros, one and empty
np.zeros((2,3))
#One
np.ones((2,3), dtype=np.int64)
#Empty
np.empty((2,3))

array([[5.e-324, 5.e-324, 5.e-324],
       [5.e-324, 5.e-324, 5.e-324]])

In [12]:
# To create sequences of numbers
np.arange(10, 41, 5)

np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [16]:
from numpy import pi
np.linspace(0, 2, 9)

x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)
f


array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -