# Basic Operations

In [1]:
import numpy as np

In [2]:
a = np.arange(20, 51, 10)
a

array([20, 30, 40, 50])

In [3]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [4]:
# Subtract
c = a - b
c

array([20, 29, 38, 47])

In [5]:
# Exponential
b**2

array([0, 1, 4, 9])

In [6]:
# multiply
10 * np.sin(a)
np.sin(20)

np.float64(0.9129452507276277)

In [7]:
# Coparative
a < 35

array([ True,  True, False, False])

In [15]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

A * B

array([[2, 0],
       [0, 4]])

In [16]:
A @ B

array([[5, 4],
       [3, 4]])

In [17]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [43]:
rg = np.random.default_rng(1) # create instance of default random number generator
a = rg.random((2,3))

# a array([[0.51182162, 0.9504637 , 0.14415961],
#         [0.94864945, 0.31183145, 0.42332645]])

a.min() # 0.14415961271963373
a.max() # 0.9504636963259353
a.sum() # 3.290252281866131


np.float64(0.5483753803110218)

In [68]:
b = np.arange(12).reshape(3,4)

# b array([[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]])

b.sum(axis=0) # sum of each column
b.sum(axis=1) # sum of each row
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])