# Basic Operations

In [1]:
import numpy as np

In [5]:
a = np.arange(20, 51, 10)
a

array([20, 30, 40, 50])

In [6]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [7]:
# Subtract
c = a - b
c

array([20, 29, 38, 47])

In [10]:
# Exponential
b**2

array([0, 1, 4, 9])

In [13]:
# multiply
10 * np.sin(a)
np.sin(20)

np.float64(0.9129452507276277)

In [12]:
# Coparative
a < 35

array([ True,  True, False, False])